topics:
  - name: "/timestamped_cal_gas"
  - name: "/timestamped_gas_v2_102b"
  - name: "/timestamped_gas_v2_302b"
  - name: "/timestamped_gas_v2_502b"
  - name: "/timestamped_gas_v2_702b"
  - name: "/timestamped_tgs_2600_analog"
  - name: "/timestamped_tgs_2602_analog"
  - name: "/timestamped_tgs_2603_analog"
