(setq *basic-cooking-target-conditions* (list
                                         '((MIXED EGG-MIXTURE EGG MILK WHISK) (IN EGG-MIXTURE BOWL))
                                         '((IN BUTTER FRYING-PAN))
                                         '((HEATED BUTTER MELT))
                                         '((IN EGG-MIXTURE FRYING-PAN))
                                         '((HEATED EGG-MIXTURE SURROUNDINGS-HARDENED))
                                         '((STIR-FRIED EGG-MIXTURE WHOLE-MIXTURE-TENDER WOODEN-SPATULA))
                                         ))
