(setq *basic-cooking-target-conditions* (list
                                         '((BOILED WATER BOILED-WATER))
                                         '((SET-STOVE LOW POT))
                                         '((STIRRED WATER VORTEXED-WATER SPOON))
                                         '((IN EGG POT))
                                         '((BOILED EGG THREE-MINUTES))
                                         ))
