#!/usr/bin/env roseus


(defun push-knob (&rest args)
  (format t "push knob! ~%")
  )

(defun push-knob-on (&rest args)
  (format t "push knob on! ~%")
  )

(defun rotate-knob (&rest args)
  (format t "rotate knob! ~%")
  )

(defun rotate-knob-right (&rest args)
  (format t "rotate knob right! ~%")
  )

(defun rotate-knob-left (&rest args)
  (format t "rotate knob left! ~%")
  )

(defun push-knob-off (&rest args)
  (format t "push knob off! ~%")
  )
