image_width: 640
image_height: 480
camera_name: narrow_stereo
camera_matrix:
  rows: 3
  cols: 3
  data: [603.76402,   0.     , 329.48773,
           0.     , 606.13592, 252.39981,
           0.     ,   0.     ,   1.     ]
distortion_model: plumb_bob
distortion_coefficients:
  rows: 1
  cols: 5
  data: [0.025594, -0.137374, 0.005265, 0.000751, 0.000000]
rectification_matrix:
  rows: 3
  cols: 3
  data: [1., 0., 0.,
         0., 1., 0.,
         0., 0., 1.]
projection_matrix:
  rows: 3
  cols: 4
  data: [600.75885,   0.     , 329.66956,   0.     ,
           0.     , 604.8092 , 253.46809,   0.     ,
           0.     ,   0.     ,   1.     ,   0.     ]
