(setq *basic-cooking-target-conditions* (list
                                         '((IN WATER POT))
                                         '((HEATED WATER BOILING))
                                         '((SET-STOVE LOW-HEAT))
                                         '((STIRRED WATER WHIRLPOOL SPOON))
                                         '((IN EGG POT))
                                         '((BOILED EGG THREE-MINUTES))
                                         ))
