(setq *basic-cooking-target-conditions* (list
                                         '((MIXED EGG-MIXTURE EGG MILK WHISK) (IN EGG-MIXTURE BOWL))
                                         '((IN BUTTER FRYING-PAN))
                                         '((HEATED BUTTER MELTED-BUTTER))
                                         '((IN EGG-MIXTURE FRYING-PAN))
                                         '((COOKED EGG-MIXTURE HALF-COOKED-EGG))
                                         '((STIR-FRIED EGG-MIXTURE SOFT-SCRAMBLED-EGG SPATULA))
                                         ))
